#Basic workflow to deploy our apis

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH and deploy python API app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTIP }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd ~/myhmbiz-api
          git config pull.rebase true
          git pull https://github.com/bulldoguk/myhmbiz-api.git main
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          echo MONGODB=${{ secrets.MONGODB }} > .env
          echo DEVELOPMENT=False >> .env
          echo "APIKEY={teFmseoVnj@/Xz#9>OamT7.WB*N,*5w!,g=I|9WZK;.UQXe$VDyz1X=cT%:ncJ" >> .env
